/************************************************************************
 *
 *     Project:  Multi-res 8514 driver
 *
 *      Module:  48dpi.h
 *
 *     Remarks:  
 *
 *    This file contains the resource ID's for the 48dpi resources for
 *    the Multi-"dpi" 8514 driver.
 *
 *    The 48 DPI resources are offset from the 96 dpi resources by 2000
 *
 *   Revisions:  
 *
 *
 ***********************************************************************/

#ifdef OEMRESOURCE

/* OEM Resource Ordinal Numbers */
#define OBM_48_CLOSE	            36754 
#define OBM_48_UPARROW              36753 
#define OBM_48_DNARROW              36752 
#define OBM_48_RGARROW              36751 
#define OBM_48_LFARROW              36750 
#define OBM_48_REDUCE               36749 
#define OBM_48_ZOOM                 36748 
#define OBM_48_RESTORE              36747 
#define OBM_48_REDUCED              36746 
#define OBM_48_ZOOMD                36745 
#define OBM_48_RESTORED             36744 
#define OBM_48_UPARROWD             36743 
#define OBM_48_DNARROWD             36742 
#define OBM_48_RGARROWD             36741 
#define OBM_48_LFARROWD             36740 
#define OBM_48_MNARROW              36739 
#define OBM_48_COMBO                36738 
#define OBM_48_UPARROWI	            36737
#define OBM_48_DNARROWI	            36736
#define OBM_48_RGARROWI	            36735
#define OBM_48_LFARROWI	            36734

#define OBM_48_OLD_CLOSE            36767 
#define OBM_48_SIZE                 36766 
#define OBM_48_OLD_UPARROW          36765 
#define OBM_48_OLD_DNARROW          36764 
#define OBM_48_OLD_RGARROW          36763 
#define OBM_48_OLD_LFARROW          36762 
#define OBM_48_BTSIZE               36761 
#define OBM_48_CHECK                36760 
#define OBM_48_CHECKBOXES           36759 
#define OBM_48_BTNCORNERS           36758 
#define OBM_48_OLD_REDUCE           36757 
#define OBM_48_OLD_ZOOM             36756 
#define OBM_48_OLD_RESTORE          36755 

/* N.B. These are only 120dpi + 2000, NOT + 4000, because there are no
 * 96dpi specific cursor resources! */
#define OCR_48_NORMAL               34512 
#define OCR_48_IBEAM                34513 
#define OCR_48_WAIT                 34514 
#define OCR_48_CROSS                34515 
#define OCR_48_UP                   34516 
#define OCR_48_SIZE                 34640 
#define OCR_48_ICON                 34641 
#define OCR_48_SIZENWSE             34642 
#define OCR_48_SIZENESW             34643 
#define OCR_48_SIZEWE               34644 
#define OCR_48_SIZENS               34645 
#define OCR_48_SIZEALL              34646 
#define OCR_48_ICOCUR               34647 

#endif /* OEMRESOURCE */
/************************************************************************
 * End of File: 48dpi.h
 ***********************************************************************/

